// Public API error codes (plan §4.1) and their HTTP status.

export const ERROR_CODES = [
  "VALIDATION_ERROR",
  "BODY_TOO_LARGE",
  "VIDEO_NOT_FOUND",
  "NOT_OWNER",
  "SEQ_CONFLICT",
  "EVENT_LIMIT",
  "INVALID_CHOICE",
  "NOT_AT_QUIZ",
  "NOT_ENDED",
  // ---------- admin (plan §4.4) ----------
  "UNAUTHENTICATED",
  "BAD_ORIGIN",
  "INVALID_CREDENTIALS",
  "TOO_MANY_ATTEMPTS",
  "VIDEO_LOCKED",
  "DUPLICATE_TRIGGER",
  "INVALID_TRIGGER",
] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];

export const ERROR_STATUS: Record<ErrorCode, number> = {
  VALIDATION_ERROR: 400,
  BODY_TOO_LARGE: 413,
  VIDEO_NOT_FOUND: 404,
  NOT_OWNER: 403,
  SEQ_CONFLICT: 409,
  EVENT_LIMIT: 429,
  INVALID_CHOICE: 400,
  NOT_AT_QUIZ: 409,
  NOT_ENDED: 422,
  UNAUTHENTICATED: 401,
  BAD_ORIGIN: 403,
  INVALID_CREDENTIALS: 401,
  TOO_MANY_ATTEMPTS: 429,
  VIDEO_LOCKED: 409,
  DUPLICATE_TRIGGER: 409,
  INVALID_TRIGGER: 422,
};
